'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.5456
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  强类型资源类，用于查找本地化字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("on_screen_ruler.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  为使用此强类型资源类的所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property a4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 About And Tips 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property about0() As String
            Get
                Return ResourceManager.GetString("about0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 关于 和 使用技巧 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property about1() As String
            Get
                Return ResourceManager.GetString("about1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 On Screen Ruler 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property appname0() As String
            Get
                Return ResourceManager.GetString("appname0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 桌面尺子 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property appname1() As String
            Get
                Return ResourceManager.GetString("appname1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property bottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 2. By Drag The Little Label On Lower Right Corner To Fix The Size Of This Panel To Your A4 Page. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property bydrag0() As String
            Get
                Return ResourceManager.GetString("bydrag0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 2. 拖动这个窗口的右下角小方块，调整这个窗口的宽度跟你文档的宽度一致 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property bydrag1() As String
            Get
                Return ResourceManager.GetString("bydrag1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Centimeters 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property centi0() As String
            Get
                Return ResourceManager.GetString("centi0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 厘米 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property centi1() As String
            Get
                Return ResourceManager.GetString("centi1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Change Background Color 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property changb0() As String
            Get
                Return ResourceManager.GetString("changb0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 修改背景颜色 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property changb1() As String
            Get
                Return ResourceManager.GetString("changb1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 切换语言 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property changelang0() As String
            Get
                Return ResourceManager.GetString("changelang0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Switch Language 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property changelang1() As String
            Get
                Return ResourceManager.GetString("changelang1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Clear Marks 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property clearmark0() As String
            Get
                Return ResourceManager.GetString("clearmark0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 清除标记 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property clearmark1() As String
            Get
                Return ResourceManager.GetString("clearmark1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 This action will clear all marks. Continue? 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property cleartip0() As String
            Get
                Return ResourceManager.GetString("cleartip0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 此操作会清除所有标记，继续吗？ 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property cleartip1() As String
            Get
                Return ResourceManager.GetString("cleartip1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Correction For In-Screen 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property corrfin0() As String
            Get
                Return ResourceManager.GetString("corrfin0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 屏幕内修正 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property corrfin1() As String
            Get
                Return ResourceManager.GetString("corrfin1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Correction For Out-Screen 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property corrfout0() As String
            Get
                Return ResourceManager.GetString("corrfout0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 屏幕外修正 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property corrfout1() As String
            Get
                Return ResourceManager.GetString("corrfout1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Donate! 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property donate0() As String
            Get
                Return ResourceManager.GetString("donate0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 赞助与捐赠！ 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property donate1() As String
            Get
                Return ResourceManager.GetString("donate1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property dot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enable Horizontal Marks 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property enhormark0() As String
            Get
                Return ResourceManager.GetString("enhormark0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 水平标记 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property enhormark1() As String
            Get
                Return ResourceManager.GetString("enhormark1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enable Vertical Marks 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property envermark0() As String
            Get
                Return ResourceManager.GetString("envermark0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 垂直标记 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property envermark1() As String
            Get
                Return ResourceManager.GetString("envermark1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Exit 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property exit0() As String
            Get
                Return ResourceManager.GetString("exit0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 退出 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property exit1() As String
            Get
                Return ResourceManager.GetString("exit1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Fix This Panel To An A4 Paper In Your Screen 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property fixthispanel0() As String
            Get
                Return ResourceManager.GetString("fixthispanel0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 将这个方块和你文档内的A4纸短边对齐 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property fixthispanel1() As String
            Get
                Return ResourceManager.GetString("fixthispanel1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property fullsize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fullsize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Help And Feed Back 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property help0() As String
            Get
                Return ResourceManager.GetString("help0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 帮助与反馈 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property help1() As String
            Get
                Return ResourceManager.GetString("help1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 History:
        '''
        '''Version V1.00  -Born
        '''Version V1.02  -Fixed bugs in correction
        '''Version V1.03  -Add change background color
        '''Version V1.04  -You can move the mark by arrow keys 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property history0() As String
            Get
                Return ResourceManager.GetString("history0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 历史：
        '''
        '''版本v1.00  -初始版本
        '''版本v1.02  -修正校正刻度问题
        '''版本v1.03  -添加修改背景颜色功能
        '''版本v1.04  -添加键盘方向键微调标记 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property history1() As String
            Get
                Return ResourceManager.GetString("history1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 How To : 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property howto0() As String
            Get
                Return ResourceManager.GetString("howto0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 怎么做： 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property howto1() As String
            Get
                Return ResourceManager.GetString("howto1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Inches 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property inche0() As String
            Get
                Return ResourceManager.GetString("inche0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 英寸 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property inche1() As String
            Get
                Return ResourceManager.GetString("inche1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property lbottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lbottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Left Ticker 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property leftticker0() As String
            Get
                Return ResourceManager.GetString("leftticker0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 左侧刻度 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property leftticker1() As String
            Get
                Return ResourceManager.GetString("leftticker1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property lsize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lsize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ltop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ltop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Change Mark Color 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property markc0() As String
            Get
                Return ResourceManager.GetString("markc0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 修改标记颜色 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property markc1() As String
            Get
                Return ResourceManager.GetString("markc1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 1. Open A Word Document, PDF Document Or Just Your Document, Then Set The Page Size To A4 And Zoom 100%. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property openaw0() As String
            Get
                Return ResourceManager.GetString("openaw0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 1. 打开你的文档，将页面设置为A4大小，然后确保页面缩放为100% 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property openaw1() As String
            Get
                Return ResourceManager.GetString("openaw1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Pixels 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property pixel0() As String
            Get
                Return ResourceManager.GetString("pixel0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 像素 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property pixel1() As String
            Get
                Return ResourceManager.GetString("pixel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Change Ruler Color 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property rulerc0() As String
            Get
                Return ResourceManager.GetString("rulerc0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 修改刻度颜色 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property rulerc1() As String
            Get
                Return ResourceManager.GetString("rulerc1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Stay On Top 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property staytop0() As String
            Get
                Return ResourceManager.GetString("staytop0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 窗口置顶 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property staytop1() As String
            Get
                Return ResourceManager.GetString("staytop1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 How To: Find a standard bank card(e.g, credit card, client card, whatever). Attach the shorter edges to the pic on lower right corner, 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property step0() As String
            Get
                Return ResourceManager.GetString("step0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 怎么做：照一张普通的银行卡（跟一般银行卡大小一致的卡也可以）。把卡的短边附在右下的图上; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property step1() As String
            Get
                Return ResourceManager.GetString("step1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 then scroll the trackbar to control the size of the pic, make sure it fixed your card correctly. Then click OK. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property stepthen0() As String
            Get
                Return ResourceManager.GetString("stepthen0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 滑动右边的滑动条，调整右下的图大小，使图大小刚好适合你的卡。 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property stepthen1() As String
            Get
                Return ResourceManager.GetString("stepthen1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 This is a Powerful on screen ruler, but it is really easy to use. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property thisis0() As String
            Get
                Return ResourceManager.GetString("thisis0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 这是一把强大而易用的桌面尺子 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property thisis1() As String
            Get
                Return ResourceManager.GetString("thisis1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Tips in using:
        '''
        '''1. You can scroll the mouse to change transparent;
        '''2. You can use this to measure thing outside your screen, but  please
        '''   use &quot;Correction For Out-Screen&quot; in right click menu first
        '''3. You can also measure your document in the screen, and the same,
        '''    please make &quot;Correction For In-Screen&quot;
        '''4. You can use arrow keys to move the mark, and press Enter or Space to mark. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tips0() As String
            Get
                Return ResourceManager.GetString("tips0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 使用技巧：
        '''
        '''1. 滚动鼠标中间可以调整窗口的透明度；
        '''2. 这把尺子可以用来测量屏幕外东西的长度，但是需要一张信用卡来校正，
        '''   详细可以右键点击“屏幕外校正”；
        '''3. 这把尺子也可以用来测量屏幕内东西的长度，需要打开A4文档来校正，详
        '''   细可以右键点击“屏幕内校正”；
        '''4. 可以使用键盘方向键移动标记，回车或空格可以Mark. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property tips1() As String
            Get
                Return ResourceManager.GetString("tips1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Top Ticker 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property topticker0() As String
            Get
                Return ResourceManager.GetString("topticker0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 顶部刻度 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property topticker1() As String
            Get
                Return ResourceManager.GetString("topticker1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Undo Last Mark 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property undomark0() As String
            Get
                Return ResourceManager.GetString("undomark0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 撤销标记 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property undomark1() As String
            Get
                Return ResourceManager.GetString("undomark1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Unit 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property unit0() As String
            Get
                Return ResourceManager.GetString("unit0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 刻度单位 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property unit1() As String
            Get
                Return ResourceManager.GetString("unit1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 3. When You Finish, Click OK. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property whenf0() As String
            Get
                Return ResourceManager.GetString("whenf0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 3. 完成后点击左边的OK按钮 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property whenf1() As String
            Get
                Return ResourceManager.GetString("whenf1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
